[package]
name = "shikra-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Shikra C2 transport, TLS material and wire framing"

[lints]
workspace = true

[dependencies]
shikra-core.workspace = true
shikra-crypto.workspace = true
shikra-proto.workspace = true
anyhow.workspace = true
base32.workspace = true
base64.workspace = true
boringtun.workspace = true
x25519-dalek.workspace = true
hex.workspace = true
prost.workspace = true
prost-types.workspace = true
rand.workspace = true
rcgen.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
