[package]
name = "shikra-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Shikra C2 protobuf definitions and generated glue"

[lints]
workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
time.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
protoc-bin-vendored.workspace = true
